/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MessageManager_H
#define MessageManager_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "test_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MessageManagerIf {
 public:
  virtual ~MessageManagerIf() {}
  virtual void add_message(message& _return, const message& m) = 0;
};

class MessageManagerIfFactory {
 public:
  typedef MessageManagerIf Handler;

  virtual ~MessageManagerIfFactory() {}

  virtual MessageManagerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MessageManagerIf* /* handler */) = 0;
};

class MessageManagerIfSingletonFactory : virtual public MessageManagerIfFactory {
 public:
  MessageManagerIfSingletonFactory(const boost::shared_ptr<MessageManagerIf>& iface) : iface_(iface) {}
  virtual ~MessageManagerIfSingletonFactory() {}

  virtual MessageManagerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MessageManagerIf* /* handler */) {}

 protected:
  boost::shared_ptr<MessageManagerIf> iface_;
};

class MessageManagerNull : virtual public MessageManagerIf {
 public:
  virtual ~MessageManagerNull() {}
  void add_message(message& /* _return */, const message& /* m */) {
    return;
  }
};

typedef struct _MessageManager_add_message_args__isset {
  _MessageManager_add_message_args__isset() : m(false) {}
  bool m :1;
} _MessageManager_add_message_args__isset;

class MessageManager_add_message_args {
 public:

  MessageManager_add_message_args(const MessageManager_add_message_args&);
  MessageManager_add_message_args& operator=(const MessageManager_add_message_args&);
  MessageManager_add_message_args() {
  }

  virtual ~MessageManager_add_message_args() throw();
  message m;

  _MessageManager_add_message_args__isset __isset;

  void __set_m(const message& val);

  bool operator == (const MessageManager_add_message_args & rhs) const
  {
    if (!(m == rhs.m))
      return false;
    return true;
  }
  bool operator != (const MessageManager_add_message_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MessageManager_add_message_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MessageManager_add_message_pargs {
 public:


  virtual ~MessageManager_add_message_pargs() throw();
  const message* m;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MessageManager_add_message_result__isset {
  _MessageManager_add_message_result__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _MessageManager_add_message_result__isset;

class MessageManager_add_message_result {
 public:

  MessageManager_add_message_result(const MessageManager_add_message_result&);
  MessageManager_add_message_result& operator=(const MessageManager_add_message_result&);
  MessageManager_add_message_result() {
  }

  virtual ~MessageManager_add_message_result() throw();
  message success;
  InvalidValueException e;

  _MessageManager_add_message_result__isset __isset;

  void __set_success(const message& val);

  void __set_e(const InvalidValueException& val);

  bool operator == (const MessageManager_add_message_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(e == rhs.e))
      return false;
    return true;
  }
  bool operator != (const MessageManager_add_message_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MessageManager_add_message_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MessageManager_add_message_presult__isset {
  _MessageManager_add_message_presult__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _MessageManager_add_message_presult__isset;

class MessageManager_add_message_presult {
 public:


  virtual ~MessageManager_add_message_presult() throw();
  message* success;
  InvalidValueException e;

  _MessageManager_add_message_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MessageManagerClient : virtual public MessageManagerIf {
 public:
  MessageManagerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MessageManagerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void add_message(message& _return, const message& m);
  void send_add_message(const message& m);
  void recv_add_message(message& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MessageManagerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MessageManagerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MessageManagerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_add_message(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MessageManagerProcessor(boost::shared_ptr<MessageManagerIf> iface) :
    iface_(iface) {
    processMap_["add_message"] = &MessageManagerProcessor::process_add_message;
  }

  virtual ~MessageManagerProcessor() {}
};

class MessageManagerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MessageManagerProcessorFactory(const ::boost::shared_ptr< MessageManagerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MessageManagerIfFactory > handlerFactory_;
};

class MessageManagerMultiface : virtual public MessageManagerIf {
 public:
  MessageManagerMultiface(std::vector<boost::shared_ptr<MessageManagerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MessageManagerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MessageManagerIf> > ifaces_;
  MessageManagerMultiface() {}
  void add(boost::shared_ptr<MessageManagerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void add_message(message& _return, const message& m) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add_message(_return, m);
    }
    ifaces_[i]->add_message(_return, m);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MessageManagerConcurrentClient : virtual public MessageManagerIf {
 public:
  MessageManagerConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MessageManagerConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void add_message(message& _return, const message& m);
  int32_t send_add_message(const message& m);
  void recv_add_message(message& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
