// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: test.proto

#include "test.pb.h"
#include "test.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace test {

static const char* Greeter_method_names[] = {
  "/test.Greeter/SendLine",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendLine_(Greeter_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::SendLine(::grpc::ClientContext* context, const ::test::Hello& request, ::test::test_line* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SendLine_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::test::test_line>* Greeter::Stub::AsyncSendLineRaw(::grpc::ClientContext* context, const ::test::Hello& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::test::test_line>(channel_.get(), cq, rpcmethod_SendLine_, context, request);
}

Greeter::Service::Service() {
  (void)Greeter_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< Greeter::Service, ::test::Hello, ::test::test_line>(
          std::mem_fn(&Greeter::Service::SendLine), this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SendLine(::grpc::ServerContext* context, const ::test::Hello* request, ::test::test_line* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test

