/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "test_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




file_content::~file_content() throw() {
}


void file_content::__set_line(const std::string& val) {
  this->line = val;
}

uint32_t file_content::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->line);
          this->__isset.line = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t file_content::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("file_content");

  xfer += oprot->writeFieldBegin("line", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeBinary(this->line);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(file_content &a, file_content &b) {
  using ::std::swap;
  swap(a.line, b.line);
  swap(a.__isset, b.__isset);
}

file_content::file_content(const file_content& other0) {
  line = other0.line;
  __isset = other0.__isset;
}
file_content& file_content::operator=(const file_content& other1) {
  line = other1.line;
  __isset = other1.__isset;
  return *this;
}
void file_content::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "file_content(";
  out << "line=" << to_string(line);
  out << ")";
}


